version: "3.8"

services:
  fsb:
      build: .
      restart: unless-stopped
      container_name: fsb
      environment:
      # required
       - API_ID=25283437 # change this to your ID
       - API_HASH=c3293e52df0923a9e0b541e949363d37 # change this to your HASH
       - BOT_TOKEN=6304190710:AAHVeD0OsUCqp6MZEm77M3ZxgCES2c15Q70 # enter your bot token
       - BIN_CHANNEL=-1001981133777 # paste channel ID
      ports:
       - 127.0.0.1:8000:8000
      volumes:
       - $HOME/TG-FileStreamBot:/app/.env
